language: csharp
mono: none
#mono: 
#  - 4.6.0
#solution: LamedalCore.sln
dotnet: 1.0.4
dist: trusty
#sudo: required
script:
 - cd build
 - cd perezLamed
 - dir
 - dotnet restore build/perezLamed/src/LamedalCore.csproj
 - dotnet build build/perezLamed/src/LamedalCore.csproj -f netstandard1.6
# - dotnet restore tests/LamedalCore.Test.csproj
# - dotnet build tests/LamedalCore.Test.csproj -f netstandard1.6
