language: csharp
mono: none
#mono: 
#  - 4.6.0
#solution: LamedalCore.sln
dotnet: 1.0.4
dist: trusty
#sudo: required
script:
 - cd build
 - cd perezLamed
 - dir
 - dotnet restore src/LamedalCore.csproj
 - dotnet restore test/LamedalCore.Test.csproj
 - dotnet build src/LamedalCore.csproj -f netstandard1.6
 - dotnet build test/LamedalCore.Test.csproj -f netstandard1.6
# - dotnet run -p src/NodaTime.Test/*.csproj -f netcoreapp1.0 -- --where=cat!=Slow
