version: 1.0.{build}
cache: packages -> **\packages.config
build_script:
- cmd: >-
    echo %CD%

    nuget restore LamedalCore.sln
notifications:
- provider: Email
  to:
  - cobus.olivier.co@gmail.com
  subject: LamedalCore Test Build Failure @ AppVeyor
  on_build_success: false
  on_build_failure: true
  on_build_status_changed: false
build:
  project: LamedalCore.sln
  verbosity: minimal  
test_script:
- cmd: xunit.console tests\bin\Debug\LamedalCore.Test.exe -appveyor
